### PR TITLE
new french file added

### PR DESCRIPTION
**Pull request by cynferdd**
Beginning of a french translation. The main work is to translate things in the needed projects (for example I started to create a french cuss file)

There's still work to see how to implement the switch from one language ot another

### CODE REVIEW

**Comment by wooorm** [comment]
@cynferdd this looks like a nice start! Thank you.

I think the interface should be as simple as possible, so that we can easily add more languages.
I think English should stay the default (`index.js`), and then `fr.js` could be the french one (and similar for other languages). Then, I’d love for there to be another file, such as `factory.js`, that does all the code and logic. It would take the cuss file, and message translations, and it would be used in `fr.js` and `index.js`

Alternatively, maybe the messages don’t need to be translated? 🤔 Only the stuff it catches?

**Comment by wooorm** [comment]
@cynferdd Anything I can do to help?

**Comment by cynferdd** [comment]
@wooorm Sorry about the lack of updates, I have a lot of things to do at work currently. I hope I'll be able to get a bit more free time soon.

**Comment by wooorm** [comment]
@cynferdd No problem!

**Pull request merged**
