### PR TITLE
Adding pik

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/google/pik/issues/6.

### CODE REVIEW

**Comment by wooorm** [comment]
Hi! 👋 Thanks for the PR!

I haven’t added words from non-English languages, so this is a first. I’m not sure if it’s feasible to do that (P.S. I’m Dutch), for one (or many?) languages!

One downside: we probably need to duplicate the project to get good coverage, doubling it in size.
Another: it would result in a lot of wrong matches: some normal words in English are profane in Dutch, and some that are normal in Dutch are profane in English.

**Comment by RichardLitt** [comment]
:wave:  

Have you looked at http://wordsafety.com/? They might have a good list to check. I think that this is important, too. Perhaps an option for other languages besides English?

**Comment by wooorm** [comment]
That looks cool! Albeit not open source?

We still need lists for Dutch / Danish (in this case) to make other languages work.
If projects for other languages are created, I can work on supporting this in alex itself!

**Comment by wooorm** [comment]
@RichardLitt Some languages done!

**Comment by RichardLitt** [comment]
:)

**Pull request closed without merging**
