### PR TITLE
add pt-br.js file

### LINKED ISSUE #12: Add pt-br.js
Hey folks, 

I will start the intenationalisation to Portuguese From Brazil, so I will create a file called pt-br.js 

Should I wrap this file in a internationalisation folder? resulting in translations/pt-br.js ? Or just leave in the root of the repository? 

Best Regards,
Otacilio Maia.

### PR DESCRIPTION
**Pull request by OtacilioN**
Starting the localisation to PT-BR

Fixes #12

### CODE REVIEW

**Review by wooorm — CHANGES_REQUESTED** [review]
Nice start! could you use English comments though? Now I don’t get what’s happening!

**Comment by Murderlon** [comment]
hi @OtacilioN, Travis is still throwing some errors, could you take a look at those?

```
  pt-br.js:38:41
  ✖  38:41  APOSTROPHES is not defined.  no-undef
  ✖  39:36  APOSTROPHES is not defined.  no-undef
```

Also, @wooorm wouldn't it be nicer to abstract away the reused logic so new language files (e.g `pt-br.js`) only contain language specific changes?

**Comment by OtacilioN** [comment]
Yeah, of course, @Murderlon I was sure that I fixed it yesterday, but probably I forgot to push the changes.

**Comment by OtacilioN** [comment]
A possibility to localisations is making a file with just the constants and exporting these constants.

**Comment by OtacilioN** [comment]
Okay, probably fixed, let's wait our Travis friend check it.

**Comment by OtacilioN** [comment]
lol:  ✖  26:23  Comments should not begin with a lowercase character  capitalized-comments

That's a very specific rule, fixing SOAP

**Comment by OtacilioN** [comment]
Now Travis has approved!

**Comment by OtacilioN** [comment]
Fixes #12

**Review by wooorm — CHANGES_REQUESTED** [review]
@OtacilioN Nice work! One more thing: could you use English for the strings as well, instead of Portuguese? I think it makes sense to use English messages even for Portuguese words!

**Comment by wooorm** [comment]
@Murderlon 

> Also, wooorm wouldn't it be nicer to abstract away the reused logic so new language files (e.g pt-br.js) only contain language specific changes?

Yep, totes, but we can do that later!

**Review by wooorm — APPROVED** [review]

**Pull request merged**
